from openai import OpenAI
import os

def llm_api(prompt: str, system_prompt: str="You are a helpful assistant") -> str:
    client = OpenAI(api_key=os.getenv("DEEPSEEK_API_KEY"), base_url="https://api.deepseek.com")

    response = client.chat.completions.create(
        model="deepseek-chat",
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": prompt},
        ],
        stream=False
    )

    resp = response.choices[0].message.content
    print(resp)
    return resp

if __name__ == "__main__":
    PROMPT_B = """\
输入：上一轮(JSON)；输出：同为 JSON 数组，但每条记录需：
1) 增加 domain ∈ {density, specific_heat, thermal_conductivity, elastoplastic_model, thermal_expansion, irradiation_creep, irradiation_swelling, corrosion, hardening}，据 property_name/test_type/上下文合理映射；
2) 统一单位（MPa, HV, wt%, ppm, °C/K, W/mK, J/kgK, 1/K, dpa, mm/y），保留见到的原始单位到 raw_unit；
3) composition_raw 解析为 composition(JSON: 元素-数值-单位)，如果未知则可为空；
4) 若仅给出模型/参数名（弹塑性模型/硬化参数等），也要归入对应 domain，value 可为 null；
5) 补充 conditions 字段的缺失键（无则为 null）。

仅输出 JSON 数组，勿夹杂其它文本。
"""


    json_str = """\
[
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Table 1",
    "evidence_span": "Zircaloy-2 Cold-rolled~ Batch A . . . 50% after annealing Sn 1.46 Fe 0.13 Cr 0.09 Ni 0.06 O 0.086",
    "alloy_name": "Zircaloy-2",
    "composition_raw": "Sn:1.46, Fe:0.13, Cr:0.09, Ni:0.06, O:0.086",
    "specimen_state": null,
    "process_step": "annealing at 800°C followed by cold-rolling 50%",
    "test_type": null,
    "property_name": "composition",
    "value": null,
    "value_min": null,
    "value_max": null,
    "unit": "wt%",
    "conditions": {},
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Table 1",
    "evidence_span": "Zircaloy-2 at 800 C Cold-rolled~ Batch B. . . 40% after annealing at 760 C Sn 1.39 Fe 0.14 Cr 0.10 Ni 0.05 O 0.101",
    "alloy_name": "Zircaloy-2",
    "composition_raw": "Sn:1.39, Fe:0.14, Cr:0.10, Ni:0.05, O:0.101",
    "specimen_state": null,
    "process_step": "annealing at 760°C followed by cold-rolling 40%",
    "test_type": null,
    "property_name": "composition",
    "value": null,
    "value_min": null,
    "value_max": null,
    "unit": "wt%",
    "conditions": {},
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Table 2",
    "evidence_span": "Annealed Longitudinal Hardness 158 VHN for Material A",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": "Annealed",
    "process_step": null,
    "test_type": "tensile test",
    "property_name": "hardness",
    "value": 158,
    "value_min": null,
    "value_max": null,
    "unit": "VHN",
    "conditions": { "temp_C": 20 },
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Table 2",
    "evidence_span": "Annealed Longitudinal 0.2% Y.S. 49.0 kpsi for Material A",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": "Annealed",
    "process_step": null,
    "test_type": "tensile test",
    "property_name": "yield strength",
    "value": 49.0,
    "value_min": null,
    "value_max": null,
    "unit": "kpsi",
    "conditions": { "temp_C": 20 },
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Table 2",
    "evidence_span": "Annealed Longitudinal U.T.S. 65.0 kpsi for Material A",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": "Annealed",
    "process_step": null,
    "test_type": "tensile test",
    "property_name": "ultimate tensile strength",
    "value": 65.0,
    "value_min": null,
    "value_max": null,
    "unit": "kpsi",
    "conditions": { "temp_C": 20 },
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Table 2",
    "evidence_span": "Annealed Longitudinal Un.El. 10.0% for Material A",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": "Annealed",
    "process_step": null,
    "test_type": "tensile test",
    "property_name": "elongation",
    "value": 10.0,
    "value_min": null,
    "value_max": null,
    "unit": "%",
    "conditions": { "temp_C": 20 },
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Table 2",
    "evidence_span": "Annealed Short-transverse Hardness 192 VHN for Material A",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": "Annealed",
    "process_step": null,
    "test_type": "tensile test",
    "property_name": "hardness",
    "value": 192,
    "value_min": null,
    "value_max": null,
    "unit": "VHN",
    "conditions": { "temp_C": 20 },
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Table 2",
    "evidence_span": "Annealed Short-transverse 0.2% Y.S. 73.0 kpsi for Material A",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": "Annealed",
    "process_step": null,
    "test_type": "tensile test",
    "property_name": "yield strength",
    "value": 73.0,
    "value_min": null,
    "value_max": null,
    "unit": "kpsi",
    "conditions": { "temp_C": 20 },
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Table 2",
    "evidence_span": "Annealed Short-transverse U.T.S. 76.0 kpsi for Material A",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": "Annealed",
    "process_step": null,
    "test_type": "tensile test",
    "property_name": "ultimate tensile strength",
    "value": 76.0,
    "value_min": null,
    "value_max": null,
    "unit": "kpsi",
    "conditions": { "temp_C": 20 },
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Table 2",
    "evidence_span": "Annealed Short-transverse Un.El. 8.0% for Material A",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": "Annealed",
    "process_step": null,
    "test_type": "tensile test",
    "property_name": "elongation",
    "value": 8.0,
    "value_min": null,
    "value_max": null,
    "unit": "%",
    "conditions": { "temp_C": 20 },
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Table 2",
    "evidence_span": "Cold-worked Longitudinal Hardness 201 VHN for Material A",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": "Cold-worked",
    "process_step": null,
    "test_type": "tensile test",
    "property_name": "hardness",
    "value": 201,
    "value_min": null,
    "value_max": null,
    "unit": "VHN",
    "conditions": { "temp_C": 20 },
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Table 2",
    "evidence_span": "Cold-worked Longitudinal 0.2% Y.S. 89.5 kpsi for Material A",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": "Cold-worked",
    "process_step": null,
    "test_type": "tensile test",
    "property_name": "yield strength",
    "value": 89.5,
    "value_min": null,
    "value_max": null,
    "unit": "kpsi",
    "conditions": { "temp_C": 20 },
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Table 2",
    "evidence_span": "Cold-worked Longitudinal U.T.S. 92.0 kpsi for Material A",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": "Cold-worked",
    "process_step": null,
    "test_type": "tensile test",
    "property_name": "ultimate tensile strength",
    "value": 92.0,
    "value_min": null,
    "value_max": null,
    "unit": "kpsi",
    "conditions": { "temp_C": 20 },
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Table 2",
    "evidence_span": "Cold-worked Longitudinal Un.El. 2.5% for Material A",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": "Cold-worked",
    "process_step": null,
    "test_type": "tensile test",
    "property_name": "elongation",
    "value": 2.5,
    "value_min": null,
    "value_max": null,
    "unit": "%",
    "conditions": { "temp_C": 20 },
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Table 2",
    "evidence_span": "Cold-worked Short-transverse Hardness 236 VHN for Material A",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": "Cold-worked",
    "process_step": null,
    "test_type": "tensile test",
    "property_name": "hardness",
    "value": 236,
    "value_min": null,
    "value_max": null,
    "unit": "VHN",
    "conditions": { "temp_C": 20 },
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Table 2",
    "evidence_span": "Cold-worked Short-transverse 0.2% Y.S. 97.0 kpsi for Material A",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": "Cold-worked",
    "process_step": null,
    "test_type": "tensile test",
    "property_name": "yield strength",
    "value": 97.0,
    "value_min": null,
    "value_max": null,
    "unit": "kpsi",
    "conditions": { "temp_C": 20 },
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Table 2",
    "evidence_span": "Cold-worked Short-transverse U.T.S. 100.0 kpsi for Material A",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": "Cold-worked",
    "process_step": null,
    "test_type": "tensile test",
    "property_name": "ultimate tensile strength",
    "value": 100.0,
    "value_min": null,
    "value_max": null,
    "unit": "kpsi",
    "conditions": { "temp_C": 20 },
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Table 2",
    "evidence_span": "Cold-worked Short-transverse Un.El. 2.0% for Material A",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": "Cold-worked",
    "process_step": null,
    "test_type": "tensile test",
    "property_name": "elongation",
    "value": 2.0,
    "value_min": null,
    "value_max": null,
    "unit": "%",
    "conditions": { "temp_C": 20 },
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Table 2",
    "evidence_span": "Annealed Longitudinal Hardness 156 VHN for Material B",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": "Annealed",
    "process_step": null,
    "test_type": "tensile test",
    "property_name": "hardness",
    "value": 156,
    "value_min": null,
    "value_max": null,
    "unit": "VHN",
    "conditions": { "temp_C": 20 },
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Table 2",
    "evidence_span": "Annealed Longitudinal 0.2% Y.S. 49.8 kpsi for Material B",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": "Annealed",
    "process_step": null,
    "test_type": "tensile test",
    "property_name": "yield strength",
    "value": 49.8,
    "value_min": null,
    "value_max": null,
    "unit": "kpsi",
    "conditions": { "temp_C": 20 },
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Table 2",
    "evidence_span": "Annealed Longitudinal U.T.S. 69.7 kpsi for Material B",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": "Annealed",
    "process_step": null,
    "test_type": "tensile test",
    "property_name": "ultimate tensile strength",
    "value": 69.7,
    "value_min": null,
    "value_max": null,
    "unit": "kpsi",
    "conditions": { "temp_C": 20 },
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Table 2",
    "evidence_span": "Annealed Longitudinal Un.El. 13.5% for Material B",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": "Annealed",
    "process_step": null,
    "test_type": "tensile test",
    "property_name": "elongation",
    "value": 13.5,
    "value_min": null,
    "value_max": null,
    "unit": "%",
    "conditions": { "temp_C": 20 },
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Table 2",
    "evidence_span": "Annealed Short-transverse Hardness 193 VHN for Material B",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": "Annealed",
    "process_step": null,
    "test_type": "tensile test",
    "property_name": "hardness",
    "value": 193,
    "value_min": null,
    "value_max": null,
    "unit": "VHN",
    "conditions": { "temp_C": 20 },
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Table 2",
    "evidence_span": "Annealed Short-transverse 0.2% Y.S. 69.7 kpsi for Material B",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": "Annealed",
    "process_step": null,
    "test_type": "tensile test",
    "property_name": "yield strength",
    "value": 69.7,
    "value_min": null,
    "value_max": null,
    "unit": "kpsi",
    "conditions": { "temp_C": 20 },
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Table 2",
    "evidence_span": "Annealed Short-transverse U.T.S. 75.4 kpsi for Material B",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": "Annealed",
    "process_step": null,
    "test_type": "tensile test",
    "property_name": "ultimate tensile strength",
    "value": 75.4,
    "value_min": null,
    "value_max": null,
    "unit": "kpsi",
    "conditions": { "temp_C": 20 },
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Table 2",
    "evidence_span": "Annealed Short-transverse Un.El. 8.5% for Material B",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": "Annealed",
    "process_step": null,
    "test_type": "tensile test",
    "property_name": "elongation",
    "value": 8.5,
    "value_min": null,
    "value_max": null,
    "unit": "%",
    "conditions": { "temp_C": 20 },
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Table 2",
    "evidence_span": "Cold-worked Longitudinal Hardness 193 VHN for Material B",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": "Cold-worked",
    "process_step": null,
    "test_type": "tensile test",
    "property_name": "hardness",
    "value": 193,
    "value_min": null,
    "value_max": null,
    "unit": "VHN",
    "conditions": { "temp_C": 20 },
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Table 2",
    "evidence_span": "Cold-worked Longitudinal 0.2% Y.S. 81.1 kpsi for Material B",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": "Cold-worked",
    "process_step": null,
    "test_type": "tensile test",
    "property_name": "yield strength",
    "value": 81.1,
    "value_min": null,
    "value_max": null,
    "unit": "kpsi",
    "conditions": { "temp_C": 20 },
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Table 2",
    "evidence_span": "Cold-worked Longitudinal U.T.S. 92.5 kpsi for Material B",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": "Cold-worked",
    "process_step": null,
    "test_type": "tensile test",
    "property_name": "ultimate tensile strength",
    "value": 92.5,
    "value_min": null,
    "value_max": null,
    "unit": "kpsi",
    "conditions": { "temp_C": 20 },
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Table 2",
    "evidence_span": "Cold-worked Longitudinal Un.El. 2.5% for Material B",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": "Cold-worked",
    "process_step": null,
    "test_type": "tensile test",
    "property_name": "elongation",
    "value": 2.5,
    "value_min": null,
    "value_max": null,
    "unit": "%",
    "conditions": { "temp_C": 20 },
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Table 2",
    "evidence_span": "Cold-worked Short-transverse Hardness 226 VHN for Material B",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": "Cold-worked",
    "process_step": null,
    "test_type": "tensile test",
    "property_name": "hardness",
    "value": 226,
    "value_min": null,
    "value_max": null,
    "unit": "VHN",
    "conditions": { "temp_C": 20 },
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Table 2",
    "evidence_span": "Cold-worked Short-transverse 0.2% Y.S. 85.3 kpsi for Material B",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": "Cold-worked",
    "process_step": null,
    "test_type": "tensile test",
    "property_name": "yield strength",
    "value": 85.3,
    "value_min": null,
    "value_max": null,
    "unit": "kpsi",
    "conditions": { "temp_C": 20 },
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Table 2",
    "evidence_span": "Cold-worked Short-transverse U.T.S. 96.7 kpsi for Material B",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": "Cold-worked",
    "process_step": null,
    "test_type": "tensile test",
    "property_name": "ultimate tensile strength",
    "value": 96.7,
    "value_min": null,
    "value_max": null,
    "unit": "kpsi",
    "conditions": { "temp_C": 20 },
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Table 2",
    "evidence_span": "Cold-worked Short-transverse Un.El. 1.5% for Material B",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": "Cold-worked",
    "process_step": null,
    "test_type": "tensile test",
    "property_name": "elongation",
    "value": 1.5,
    "value_min": null,
    "value_max": null,
    "unit": "%",
    "conditions": { "temp_C": 20 },
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Experimental",
    "evidence_span": "The average grain size of the annealed specimens was 20 microns.",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": "Annealed",
    "process_step": null,
    "test_type": null,
    "property_name": "grain size",
    "value": 20,
    "value_min": null,
    "value_max": null,
    "unit": "microns",
    "conditions": {},
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Experimental",
    "evidence_span": "the majority of grains had basal-plane normals oriented 30 deg from the sheet-normal direction",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": null,
    "process_step": null,
    "test_type": null,
    "property_name": "texture",
    "value": 30,
    "value_min": null,
    "value_max": null,
    "unit": "deg",
    "conditions": {},
    "metric_type": "measurement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Abstract",
    "evidence_span": "The material exhibited strong dynamic strain aging which reached maximum intensity around 300 C",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": null,
    "process_step": null,
    "test_type": null,
    "property_name": "strain aging intensity",
    "value": null,
    "value_min": null,
    "value_max": null,
    "unit": null,
    "conditions": { "temp_C": 300 },
    "metric_type": "judgement",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Results",
    "evidence_span": "Optical and electron microscope investigations of crept specimens revealed the formation of kink bands and a cell structure",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": "crept",
    "process_step": null,
    "test_type": "microscopy",
    "property_name": "microstructure",
    "value": "kink bands and cell structure",
    "value_min": null,
    "value_max": null,
    "unit": null,
    "conditions": {},
    "metric_type": "observation",
    "confidence": 0.9
  },
  {
    "source_id": "核材料文档3",
    "page_or_fig": "Results",
    "evidence_span": "little or no twinning",
    "alloy_name": "Zircaloy-2",
    "composition_raw": null,
    "specimen_state": "crept",
    "process_step": null,
    "test_type": "microscopy",
    "property_name": "twinning",
    "value": "little or no",
    "value_min": null,
    "value_max": null,
    "unit": null,
    "conditions": {},
    "metric_type": "observation",
    "confidence": 0.9
  }
]

    """

    b_prompt = PROMPT_B + "\n\n【上一轮输出】\n" + json_str

    llm_api(b_prompt)  # 测试调用